//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateData
    {
        public int CanadidateID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string StreetAddress { get; set; }
        public string Apartment { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string DateAvailable { get; set; }
        public string SocialSecurityNo { get; set; }
        public string DesiredIncome { get; set; }
        public string PositionAppliedFor { get; set; }
        public Nullable<bool> UsCitiZen { get; set; }
        public Nullable<bool> AuthorizedForWork { get; set; }
        public Nullable<bool> WorkedHere { get; set; }
        public string IfYesWhen { get; set; }
        public Nullable<bool> Convicted { get; set; }
        public string IfYesExplain { get; set; }
        public string HighSchool { get; set; }
        public string Address { get; set; }
        public string SchoolFrom1 { get; set; }
        public string SchoolTo1 { get; set; }
        public Nullable<bool> DidYouGraduated1 { get; set; }
        public string Diploma { get; set; }
        public string College { get; set; }
        public string SchoolAddress { get; set; }
        public string SchoolFrom2 { get; set; }
        public string SchoolTo2 { get; set; }
        public Nullable<bool> DidYouGraduated2 { get; set; }
        public string Deegre1 { get; set; }
        public string Other { get; set; }
        public string DeegreAddress { get; set; }
        public string SchoolFrom3 { get; set; }
        public string SchoolTo3 { get; set; }
        public Nullable<bool> DidYouGraduated3 { get; set; }
        public string Deegre2 { get; set; }
        public string RefFullName1 { get; set; }
        public string RefRelationShip1 { get; set; }
        public string RefCompany1 { get; set; }
        public string RefPhone1 { get; set; }
        public string RefAddress1 { get; set; }
        public string RefFullName2 { get; set; }
        public string RefRelationShip2 { get; set; }
        public string RefCompany2 { get; set; }
        public string RefPhone2 { get; set; }
        public string RefAddress2 { get; set; }
        public string RefFullName3 { get; set; }
        public string RefRelationShip3 { get; set; }
        public string RefCompany3 { get; set; }
        public string RefPhone3 { get; set; }
        public string RefAddress3 { get; set; }
        public string CompanyName1 { get; set; }
        public string CompanyPhone1 { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanySupervisor1 { get; set; }
        public string JobTitle1 { get; set; }
        public string StartingSalary1 { get; set; }
        public string EndingSalary1 { get; set; }
        public string Responsibilities1 { get; set; }
        public string CompanyFrom1 { get; set; }
        public string CompanyTo1 { get; set; }
        public string ReasonForLeaving1 { get; set; }
        public Nullable<bool> CanContactSV1 { get; set; }
        public string CompanyName2 { get; set; }
        public string CompanyPhone2 { get; set; }
        public string CompanyAddress2 { get; set; }
        public string CompanySupervisor2 { get; set; }
        public string JobTitle2 { get; set; }
        public string StartingSalary2 { get; set; }
        public string EndingSalary2 { get; set; }
        public string Responsibilities2 { get; set; }
        public string CompanyFrom2 { get; set; }
        public string CompanyTo2 { get; set; }
        public string ReasonForLeaving2 { get; set; }
        public Nullable<bool> CanContactSV2 { get; set; }
        public string CompanyName3 { get; set; }
        public string CompanyPhone3 { get; set; }
        public string CompanyAddress3 { get; set; }
        public string CompanySupervisor3 { get; set; }
        public string JobTitle3 { get; set; }
        public string StartingSalary3 { get; set; }
        public string EndingSalary3 { get; set; }
        public string Responsibilities3 { get; set; }
        public string CompanyFrom3 { get; set; }
        public string CompanyTo3 { get; set; }
        public string ReasonForLeaving3 { get; set; }
        public Nullable<bool> CanContactSV3 { get; set; }
        public string MilitaryBranch { get; set; }
        public string MilitaryFrom { get; set; }
        public string MilitaryTo { get; set; }
        public string RankAtDischarge { get; set; }
        public string TypeOFDischarge { get; set; }
        public string Explanation { get; set; }
        public string SignatureName { get; set; }
        public string Date { get; set; }
        public string ResumeDetails { get; set; }
    }
}
