//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentUpload
    {
        public int docUpload_id { get; set; }
        public int UserId { get; set; }
        public int doc_id { get; set; }
        public string doctypename { get; set; }
        public string filepath { get; set; }
    
        public virtual User User { get; set; }
    }
}
