//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverVehicleCargo
    {
        public int VehicleCargoID { get; set; }
        public Nullable<int> DriverVehicleID { get; set; }
        public string CargoCarriedName { get; set; }
    }
}
