//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadNote
    {
        public int LeadNoteID { get; set; }
        public string Note { get; set; }
        public string Timeline { get; set; }
        public Nullable<int> LeadID { get; set; }
        public string NoteLeftAt { get; set; }
    }
}
