//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAnalytic
    {
        public int AnalyticsID { get; set; }
        public string Date { get; set; }
        public string Username { get; set; }
        public string IPAddress { get; set; }
        public string Platform { get; set; }
        public string OS { get; set; }
        public string Browser { get; set; }
    }
}
