//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCSaleTemp
    {
        public int MCID { get; set; }
        public string DotNo { get; set; }
        public string MCNo { get; set; }
        public string NameOnCard { get; set; }
        public string AddressOnCard { get; set; }
        public string PhysicalAddress { get; set; }
        public string Email { get; set; }
        public string SavedAt { get; set; }
        public Nullable<int> SalesPersonID { get; set; }
        public string CardNo { get; set; }
        public string CardType { get; set; }
        public string ExpirationDate { get; set; }
        public string CVC { get; set; }
        public string PhoneNo { get; set; }
        public string MCSaleNo { get; set; }
        public string LegalName { get; set; }
        public string DBA { get; set; }
        public string DotPin { get; set; }
    }
}
