//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuantumEntities : DbContext
    {
        public QuantumEntities()
            : base("name=QuantumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<UserData> UserDatas { get; set; }
        public DbSet<DailySalesRecord> DailySalesRecords { get; set; }
        public DbSet<ComplianceUser> ComplianceUsers { get; set; }
        public DbSet<Lead> Leads { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<CandidateData> CandidateDatas { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<LeadDoc> LeadDocs { get; set; }
        public DbSet<DailyLead> DailyLeads { get; set; }
        public DbSet<LeadNote> LeadNotes { get; set; }
        public DbSet<AuthenticationToken> AuthenticationTokens { get; set; }
        public DbSet<DocumentMaster> DocumentMasters { get; set; }
        public DbSet<UserDocument> UserDocuments { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<LoginAnalytic> LoginAnalytics { get; set; }
        public DbSet<DocumentAnalytic> DocumentAnalytics { get; set; }
        public DbSet<MCSale> MCSales { get; set; }
        public DbSet<MCSaleTemp> MCSaleTemps { get; set; }
        public DbSet<MCServiceSale> MCServiceSales { get; set; }
        public DbSet<MCServiceSaleTemp> MCServiceSaleTemps { get; set; }
        public DbSet<DriverInterviewProfile> DriverInterviewProfiles { get; set; }
        public DbSet<DriverService> DriverServices { get; set; }
        public DbSet<DriverVehicleCargo> DriverVehicleCargoes { get; set; }
        public DbSet<OrderForm> OrderForms { get; set; }
        public DbSet<ProfileCard> ProfileCards { get; set; }
        public DbSet<DriverVehicle> DriverVehicles { get; set; }
    }
}
