//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileCard
    {
        public int ProfileCardInfo { get; set; }
        public Nullable<int> OrderFormID { get; set; }
        public string CardType { get; set; }
        public string CorDC { get; set; }
        public string Expiration { get; set; }
        public string CVC { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
    }
}
