//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public string DailySaleAmount { get; set; }
        public string Refunds { get; set; }
        public string NetSales { get; set; }
        public string MonthlySales { get; set; }
        public string CashBonus { get; set; }
        public string DrawTakenInMonth { get; set; }
        public string DailyBonus { get; set; }
        public string MonthlyOfficeRent { get; set; }
        public string QBTotalPay { get; set; }
        public Nullable<int> SalesPersonID { get; set; }
        public string EntryDate { get; set; }
        public string CommisionInUSD { get; set; }
        public string CommisionPercentage { get; set; }
    }
}
