//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TransactionCurrency { get; set; }
        public string Cryptoamount { get; set; }
        public string NoOfCoins { get; set; }
        public string TransactionTime { get; set; }
    }
}
